version: '3.8'

services:
  
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./src/Web/Dockerfile
    environment:      
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SERVICE_URL=http://service:8080
    ports:
      - '80:80'

  service:
    container_name: service
    build:
      context: .
      dockerfile: ./src/Service/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DB_HOST=db
    ports:
      - '8080:8080'